### PR TITLE
style: Make format for all files

### PR DESCRIPTION
**Pull request by philipphofmann**
The vendor folder was not included in the list of folders for
clang-format and therefore not formatted. Use find to search
for all .h, .c and .cpp files and call clang-format on them.

### CODE REVIEW

**Comment by jan-auer** [comment]
That was intentional, since we didn't want to reformat vendored files. What's the reason for formatting them?

**Comment by Swatinem** [comment]
IMO its a lot easier to keep track of upstream changes if you just include them verbatim without any reformatting.

**Comment by philipphofmann** [comment]
We are also introducing Clang-Format in sentry-cocoa and I checked out this repo to find out if you use it. I stumbled across the makefile and wanted to format all files in cocoa. Therefore I came up with using `find` and I thought maybe it improves the code here as well. It only took me 10 minutes. If you don't find it useful we can close this PR. I could have also asked before.

**Comment by Swatinem** [comment]
I definitely appreciate the effort ;-)

**Comment by jan-auer** [comment]
Thanks for bringing this up, @philipphofmann!

**Pull request closed without merging**
