### PR TITLE
fix: Allow static recursive Mutex on musl-libc

### PR DESCRIPTION
**Pull request by Swatinem**

### CODE REVIEW

**Review by flub — APPROVED** [review]
do we have a musl build on the CI?

**Comment by Swatinem** [comment]
Not yet, and TBH, I haven’t tested this on my own linux yet either.

**Comment by ericriff** [comment]
https://github.com/getsentry/sentry-native/issues/498#issuecomment-813416905

**Comment by ericriff** [comment]
I can confirm this builds with `SENTRY_BACKEND=crashpad` and `SENTRY_BACKEND=inproc`. Unfortunately I can't test it now.
`breakpad` doesn't build on mips+musl.

**Pull request merged**
