### PR TITLE
Support custom curl library

### PR DESCRIPTION
**Pull request by zhaowq32**

### CODE REVIEW

**Comment by supervacuus** [comment]
Can you explain what you are trying to achieve here?

Our build script already allows specifying your own `libcurl` build. You can add your `libcurl`-install path to the `CMAKE_PREFIX_PATH` or specify `CURL_INCLUDE_DIR` and `CURL_LIBRARY`. You don't need to make any changes.

**Comment by zhaowq32** [comment]
I compile sentry on Linux and get an error "CURL: Required feature AsynchDNS is not found".
```
cmake -G "Ninja" -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX="build/dest" -DBUILD_SHARED_LIBS=OFF -DSENTRY_BACKEND=inproc -DSENTRY_BUILD_EXAMPLES=OFF -DSENTRY_BUILD_SHARED_LIBS=OFF -DSENTRY_BUILD_TESTS=OFF -DSENTRY_TRANSPORT=curl -DCURL_INCLUDE_DIR=/test/libcurl/Debug/include -DCURL_LIBRARY=/test/libcurl/Debug/lib/libcurl.a ..     
```

**Comment by supervacuus** [comment]
> I compile sentry on Linux and get an error "CURL: Required feature AsynchDNS is not found".

Ok, but the solution to that problem isn't to bypass the check for `AsynchDNS` in the build script (which we also do at runtime).

You must check in your `libcurl` build configuration whether the `AsynchDNS` feature is enabled:

```
-- Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz SSL threadsafe UnixSockets
```

after which ours will take it up during configuration:

```
-- Found CURL: /curl/build/lib/libcurl.a (found version "8.11.1-DEV") found components: AsynchDNS 
-- Configuring done
-- Generating done
-- Build files have been written to: /sentry-native/build
```

Tested on Ubuntu 22.04 with CMake 3.22.1.

**Comment by zhaowq32** [comment]
What is your compilation command? I tried it again and still got an error.

1. cmake command for curl
```
cmake -G Ninja -DCMAKE_MAKE_PROGRAM=cmake/3.10.2.4988404/bin/ninja -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=curl-8.10.1/build/dest -DBUILD_SHARED_LIBS=OFF -DCURL_USE_OPENSSL=ON -DHTTP_ONLY=ON -DBUILD_CURL_EXE=OFF -DBUILD_TESTING=OFF -DCURL_USE_LIBSSH2=OFF -DUSE_NGHTTP2=OFF -DBUILD_LIBCURL_DOCS=OFF -DBUILD_MISC_DOCS=OFF -DENABLE_CURL_MANUAL=OFF -DENABLE_ARES=ON -DOPENSSL_ROOT_DIR=libs/linux/boringssl/Debug -DCARES_LIBRARY=libs/linux/cares/Debug/lib/libcares.a -DCARES_INCLUDE_DIR=libs/linux/cares/Debug/include -DCMAKE_DEBUG_POSTFIX= -DENABLE_DEBUG=ON ..
```

2. curl log
```
-- Features: alt-svc AsynchDNS Debug HSTS HTTPS-proxy IPv6 Largefile NTLM SSL threadsafe TrackMemory UnixSockets
```

3. sentry log
```
-- SENTRY_TRANSPORT=curl
-- SENTRY_BACKEND=inproc
-- SENTRY_LIBRARY_TYPE=STATIC
-- SENTRY_SDK_NAME=
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long
-- Check size of long - done
CMake Error at cmake-3.23/Modules/FindCURL.cmake:175 (message):
  CURL: Required feature AsynchDNS is not found
Call Stack (most recent call first):
  CMakeLists.txt:281 (find_package)
```

**Comment by zhaowq32** [comment]
I think it's because I only copied the static library but not the pkg and cmake files.

**Comment by supervacuus** [comment]
> I think it's because I only copied the static library but not the pkg and cmake files.

That makes sense. It is generally a good idea to source self-built dependencies from whatever they generate as their `install` output (i.e., `cmake --install ...` if you use CMake to build `libcurl`).

**Pull request closed without merging**
