### PR TITLE
Add support for Qt 6

### PR DESCRIPTION
**Pull request by torarnv**

### CODE REVIEW

**Comment by torarnv** [comment]
@bruno-garcia

**Review by bruno-garcia — COMMENTED** [review]
LGTM but @Swatinem might have thoughts

**Comment by torarnv** [comment]
Just a sec, let me push an update

**Comment by torarnv** [comment]
Ok, ready @Swatinem  :)

**Review by Swatinem — APPROVED** [review]
So this means if you have both development packages installed, you will always the 6 rather than 5. Is there a way to control that?

**Comment by torarnv** [comment]
> So this means if you have both development packages installed, you will always the 6 rather than 5. Is there a way to control that?

Correct, that's the current behavior. There is [`QT_DEFAULT_MAJOR_VERSION` ](https://doc.qt.io/qt-6/cmake-variable-reference.html#qt-default-major-version), but I need to check with our CMake experts whether that is applicable here. If not I could add custom logic to take it into account in a followup perhaps?

**Comment by torarnv** [comment]
Fixed. You can now choose the version with ` QT_DEFAULT_MAJOR_VERSION`

**Comment by bruno-garcia** [comment]
@Swatinem Docs are landing too: https://github.com/getsentry/sentry-docs/pull/3370
Since it's approved by you, anything blocking to merge? 🥳

**Review by Swatinem — APPROVED** [review]

**Pull request merged**
