### PR TITLE
feat: crashpad handler http-proxy support

### LINKED ISSUE #788: Adapt the crashpad transports to support HTTP proxies
While all transport implementations of the Native SDK currently support simple HTTP forwarding proxies, `crashpad` doesn't configure them in its transports. Users who configure the Native SDK with an HTTP proxy and use crashpad as a backend will receive events, but no crashes when running behind a proxy.

### PR DESCRIPTION
**Pull request by supervacuus**
fixes #788 together with https://github.com/getsentry/crashpad/pull/86

### CODE REVIEW

**Comment by supervacuus** [comment]
The macOS tests failed because ATS doesn't allow (insecure) HTTP requests (which we use in our integration tests) 🙄. ATS was also a recurring issue during testing (in other scenarios), so I changed the transport code in the handler to fall back on `NSURLConnection` if no HTTP proxy is configured, which also means that all current implementations in the wild won't be surprised/affected by ATS restrictions that introduced under the hood.

**Review by markushi — APPROVED** [review]
LGTM!

**Comment by supervacuus** [comment]
> LGTM!

just to be sure, does that include the [actual change](https://github.com/getsentry/crashpad/pull/86) in the crashpad fork too, or is this approval for the adaptation of the crashpad-backend in the Native SDK?

**Comment by markushi** [comment]
> > LGTM!
> 
> just to be sure, does that include the [actual change](https://github.com/getsentry/crashpad/pull/86) in the crashpad fork too, or is this approval for the adaptation of the crashpad-backend in the Native SDK?

My bad: This is just the review for the adaption, I just did a review for the crashpad fork too.

**Pull request merged**
