### PR TITLE
[NDK] Properly apply code formatting

### PR DESCRIPTION
**Pull request by markushi**
Unfortunately the spotless plugin wasn't applied correctly, so the Java/Kotlin code formatting was incorrect. This PR fixes the mentioned issues and provides a Makefile within the `ndk` folder, giving us an easy to use `make all` command.

#skip-changelog

### CODE REVIEW

**Review by supervacuus — APPROVED** [review]
spotless 😅

**Comment by supervacuus** [comment]
> Unfortunately the spotless plugin wasn't applied correctly, so the Java/Kotlin code formatting was incorrect. This PR fixes the mentioned issues and provides a Makefile within the `ndk` folder, giving us an easy to use `make all` command.

just one question: this only affects sentry-android major 7, right? For 8 sentry-android no longer cares how spotless the `ndk` folder is, right?

**Comment by markushi** [comment]
> > Unfortunately the spotless plugin wasn't applied correctly, so the Java/Kotlin code formatting was incorrect. This PR fixes the mentioned issues and provides a Makefile within the `ndk` folder, giving us an easy to use `make all` command.
> 
> just one question: this only affects sentry-android major 7, right? For 8 sentry-android no longer cares how spotless the `ndk` folder is, right?

This change affects none of them, as `7.x` isn't using the ndk folder at all (it pulls in an compiles sentry-native directly), and `8.x` consumes the pre-built maven artifact.

So the main motivation is to make future changes within the `ndk` folder easier and more consistent 😊

**Comment by supervacuus** [comment]
> change affects none of them, as `7.x` isn't using the ndk folder at all (it pulls in an compiles sentry-native directly)

I understand that, but was it a `7.x` build where `spotless` "saw" the `ndk` subfolder from the `sentry-native` submodule that revealed mis-formatted code?

**Comment by markushi** [comment]
> > change affects none of them, as `7.x` isn't using the ndk folder at all (it pulls in an compiles sentry-native directly)
> 
> I understand that, but was it a `7.x` build where `spotless` "saw" the `ndk` subfolder from the `sentry-native` submodule that revealed mis-formatted code?

Ah I see, `7.x.x` simply ignores the whole `sentry-native` folder: https://github.com/getsentry/sentry-java/blob/3d24791bd1b80d3dbf8a849d9f23bf14445902c9/build.gradle.kts#L229

**Pull request merged**
