### PR TITLE
improve 'sentry_options_set_logger' add 'userdata'

### PR DESCRIPTION
**Pull request by irov**
Hello, i some improve sentry logger, add 'userdata' for callback.

Thanks!

### CODE REVIEW

**Comment by irov** [comment]
> looking good, but this is a breaking change technically, now that the logger has been released.

I do not think that this slight improvement can be called a major change. Maybe this could be expanded as an improvement in the next release? ;)

**Comment by Mixaill** [comment]
> do not think that this slight improvement can be called a major change. 

It breaks API compatibility with the 0.3.2 so it is a major chnage :)

**Comment by irov** [comment]
> It breaks API compatibility with the 0.3.2 so it is a major change which requires version bump to 0.4.0 at least :)

Give thanks! And I hope that my gray hair will not cover my whole head by then! In the meantime, I'll make a crutch through a global variable

**Comment by Swatinem** [comment]
Lol, don’t worry. While those are not semver-breaking, I think the addition of windows breakpad + inproc backend are large enough changes to warrant a `0.4` release ;-) I hope to get those in during the week.

**Comment by Swatinem** [comment]
I was preparing a separate struct and global for this: https://github.com/getsentry/sentry-native/commit/5bff34a4018979d4fcc42cd472258ac8452aceb6
Please rebase on top of that.

**Comment by irov** [comment]
maybe I will create a new pull request, my first rebase failed :(

**Comment by Swatinem** [comment]
I merged this now as part of #325 , thanks!

**Pull request closed without merging**
